name: Python Mecab Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install MeCab and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mecab libmecab-dev mecab-ipadic-utf8
        git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
        cd mecab-ipadic-neologd
        ./bin/install-mecab-ipadic-neologd -n -y
        python -m pip install --upgrade pip
        pip install mecab-python3

    - name: Set MECABRC environment variable
      run: echo "export MECABRC='/usr/local/etc/mecabrc'" >> $GITHUB_ENV

    - name: Run tests
      run: python -m unittest discover tests

